version: '3.8'

services:
  bank-service-postgres:
    container_name: bank-service-postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - bank_service_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bank-db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  bank-rest:
    container_name: bank-rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      bank-service-postgres:
        condition: service_healthy

volumes:
  bank_service_postgres_data:
